# Generated by Django 4.0.4 on 2022-05-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salon',
            name='latitude',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='salon',
            name='longitude',
            field=models.FloatField(default=120),
        ),
    ]
