# Generated by Django 4.0.4 on 2022-05-04 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0002_alter_salon_latitude_alter_salon_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
