# Generated by Django 4.0.4 on 2022-05-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0003_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salon_id',
            field=models.IntegerField(default=0),
        ),
    ]
