# Generated by Django 4.0.4 on 2022-05-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_even_days',
            field=models.BooleanField(default=False),
        ),
    ]
