# Generated by Django 4.0.4 on 2022-05-12 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0006_employee_is_even_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Start Date'),
        ),
    ]
