# Generated by Django 4.0.4 on 2022-05-12 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0008_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Start Date'),
        ),
    ]
