# Generated by Django 4.0.4 on 2022-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0009_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Start Date'),
        ),
    ]
