# Generated by Django 4.0.4 on 2022-05-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0010_alter_appointments_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='service_id',
        ),
        migrations.AddField(
            model_name='appointments',
            name='services_ids',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Start Date'),
        ),
    ]
