# Generated by Django 4.0.4 on 2022-05-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonServices', '0012_employee_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
